### PR TITLE
Allow notifications to be ignored if contain specific keywords

### PR DESCRIPTION
**Pull request by ammgws**
Added ability to ignore notifications (prevent from showing) if they contain specific keywords set in the config file.

Useful if you have many devices and would rather configure it once server side rather than fiddling with the notification settings in the app on each device.

Might have it search the notificaiton message text too.

### CODE REVIEW

**Comment by rootkiwi** [comment]
Great thank you, this can be useful! You say WIP, you want to add something before I merge this? Like the message text? I'm ok either way.

**Comment by ammgws** [comment]
I thought I would leave it open for comments and if there are any other things we could add them in before merging.

For example I saw that appname isn't sent by the client to the server, but that could be pretty useful server side in terms of logging and ignoring etc. However I haven't had time to play with the client app code yet.

**Comment by rootkiwi** [comment]
Okey yea sure.

Yes the appname is not sent, but that could be useful as you say. Also support for logging on server side would be nice.

**Comment by ammgws** [comment]
Should we merge this for now and leave the other features to another PR?

**Comment by rootkiwi** [comment]
Yes, merging now. Thank you!

**Pull request merged**
