### PR TITLE
Feature/filtering messages by content regex

### PR DESCRIPTION
**Pull request by fmtovland**
I wasn't happy with the filter by keywords thing, so I threw in regex support, and as I understand the GPL I've got to give the code back so here?

### CODE REVIEW

**Comment by fmtovland** [comment]
Might have found an error: please don't go merging this yet

**Comment by rootkiwi** [comment]
Great thanks! Right, will wait, let me know how it goes

**Comment by fmtovland** [comment]
That should fix it, and I can't think of any other errors introduced off the top of my head. Sorry for opening pull request without testing. bad behavior occured when no regex filters were set, so testing with regex filter set seemed to work.

**Comment by rootkiwi** [comment]
No problem, thank you for your contribution

**Pull request merged**
